# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJZvOvKTzGfeLsEn_yUcMABap6_4wLYV
"""
 streamlit torch

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import torch.nn as nn
# 
# class SimpleModel(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.fc1 = nn.Linear(4, 8)
#         self.fc2 = nn.Linear(8, 1)
#         self.sigmoid = nn.Sigmoid()
# 
#     def forward(self, x):
#         x = torch.relu(self.fc1(x))
#         x = self.fc2(x)
#         return self.sigmoid(x)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# model = SimpleModel()
# model.load_state_dict(torch.load("/content/simple_model.pth", map_location="cpu"))
# model.eval()
# st.title("🧬 Drug Toxicity Predictor")
# 
# # ✅ REPLACE HERE
# f1 = st.number_input("Molecular Weight", value=0.0)
# f2 = st.number_input("H-Bond Donors", value=0.0)
# f3 = st.number_input("H-Bond Acceptors", value=0.0)
# f4 = st.number_input("LogP (Lipophilicity)", value=0.0)
# 
# features = [f1, f2, f3, f4]
# 
# # Prediction
# if st.button("Predict"):
#     x = torch.tensor([features], dtype=torch.float32)
# 
#     with torch.no_grad():
#         prob = model(x).item()
#     st.write("Raw Probability:", prob)
# 
#     st.write(f"Probability: {prob:.4f}")
#     st.write(f"🧪 Toxicity Risk: {prob*100:.2f}%")
# 
#     if prob > 0.6:
#         st.error("⚠️ Toxic")
#     else:
#         st.success("✅ Non-Toxic")
#

!ls

!streamlit run app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false &
!npx localtunnel --port 8501

